server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/optical_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: optical-multi-branch-super-secure-secret-2024
  expiration: 86400000

